spring:
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sdw2023
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
<<<<<<< HEAD
        web-allow-others: false

  springdoc:
      api-docs:
        enabled: true
      swagger-ui:
        path: /swagger-ui.html
        enabled: true
=======
        web-allow-others: false
>>>>>>> 83b83bf4719d137d0b58b6b53871cdb2017d8498
